blog/plans/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, Length, Email,ValidationError
from blog.models import Plan
from wtforms.fields.html5 import DateField



class AddPlanForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=20)])
    date_start = DateField('Date start', validators=[DataRequired()])
    date_end = DateField('Date end', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Save')

    def validate_title(self, title):
        plan = Plan.query.filter_by(title=title.data).first()
        if plan:
            raise ValidationError('That title is taken. Please choose a different one.')


class EditPlanForm(FlaskForm):
    id =  IntegerField('id')
    title = StringField('Title', validators=[DataRequired(), Length(min=2, max=20)])
    date_start = StringField('Date start', validators=[DataRequired()])
    date_end = StringField('Date end', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Save')

    def validate_email(self, title):
        plan = Plan.query.filter_by(title=title.data).first()
        if plan and plan.id != self.id.data:
            raise ValidationError('That title is taken. Please choose a different one.')

blog/plans/routes.py
from flask import Blueprint, url_for, render_template, flash,redirect, request
from blog.plans.forms import AddPlanForm, EditPlanForm
from blog.models import Plan
from flask_login import login_required
from blog import db

plans = Blueprint('plans',__name__)


@plans.route("/plan")
@login_required
def index():
    plans = Plan.query.all()
    return render_template('plan/index.html', plans=plans)


@plans.route("/plan/create", methods=['GET', 'POST'])
def create():
    form = AddPlanForm()
    if form.validate_on_submit():
        plan = Plan(
            title=form.title.data, 
            date_start=form.date_start.data,
            date_end=form.date_end.data,
            content=form.content.data,
        )
        db.session.add(plan)
        db.session.commit()
        flash('Your plan has been created!', 'success')
        return redirect(url_for('plans.index'))
    return render_template('plan/create.html', form = form)



@plans.route("/plan/<int:plan_id>/edit", methods=['GET', 'POST'])
@login_required
def update(plan_id):
    plan = Plan.query.get_or_404(plan_id)
    form = EditPlanForm()
    if form.validate_on_submit():
        plan.title = form.title.data
        plan.date_start = form.date_start.data
        plan.date_end = form.date_end.data
        plan.content = form.content.data
        db.session.commit()
        flash('Your plan has been updated!', 'success')
        return redirect(url_for('plans.update', plan_id=plan.id))
    elif request.method == 'GET':
        form.id.data = plan.id
        form.title.data = plan.title
        form.date_start.data = plan.date_start
        form.date_end.data = plan.date_end
        form.content.data = plan.content
    return render_template('plan/edit.html', title='Update Plan',
                           form=form)

@plans.route("/plan/<int:plan_id>/delete", methods=['POST'])
@login_required
def delete_plan(plan_id):
    plan = Plan.query.get_or_404(plan_id)
    db.session.delete(plan)
    db.session.commit()
    flash('Your plan has been deleted!', 'success')
    return redirect(url_for('plans.index'))

blog/templates/plan/create.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Candidate</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.date_start.label(class="form-control-label") }}
                    {% if form.date_start.errors %}
                        {{ form.date_start(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.date_start.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date_start(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.date_end.label(class="form-control-label") }}
                    {% if form.date_end.errors %}
                        {{ form.date_end(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.date_end.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date_end(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

blog/templates/plan/edit.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Candidate</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.date_start.label(class="form-control-label") }}
                    {% if form.date_start.errors %}
                        {{ form.date_start(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.date_start.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date_start(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.date_end.label(class="form-control-label") }}
                    {% if form.date_end.errors %}
                        {{ form.date_end(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.date_end.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date_end(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

blog/templates/plan/index.html
{% extends "layout.html" %}
{% block content %}
<table class="table">
	<thead>
		<tr>
			<th>Title</th>
			<th>Date start</th>
			<th>Date end</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for item in plans %}
		<tr>
			<td>{{ item.title }}</td>
			<td>{{ item.date_start.strftime('%Y-%m-%d') }}</td>
			<td>{{ item.date_end.strftime('%Y-%m-%d') }}</td>
			<td>
				<a href="{{ url_for('plans.update', plan_id=item.id) }}"><button type="button" class="btn btn-info btn-sm m-1">Edit</button></a>
				<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{item.id}}">Delete</button>
			</td>
		</tr>   
		<div class="modal fade" id="deleteModal{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Delete Plan?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<form action="{{ url_for('plans.delete_plan', plan_id=item.id) }}" method="POST">
							<input class="btn btn-danger" type="submit" value="Delete">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</tbody>
</table>



{% endblock content %}