blog/candidates/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, Email,ValidationError
from blog.models import Candidate

class AddCandidateForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=20)])
    phone = StringField('Phone', validators=[DataRequired(), Length(min=2, max=20)])
    address = StringField('Address', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    position = StringField('Position', validators=[DataRequired()])
    plan_id = SelectField('Plan requirement', validators=[DataRequired()],coerce=int)
    submit = SubmitField('Save')

    def validate_email(self, email):
        candidate = Candidate.query.filter_by(email=email.data).first()
        if candidate:
            raise ValidationError('That email is taken. Please choose a different one.')


   
class EditCandidateForm(FlaskForm):
    id =  IntegerField('id')
    name = StringField('Name', validators=[DataRequired(), Length(min=2, max=20)])
    phone = StringField('Phone', validators=[DataRequired(), Length(min=2, max=20)])
    address = StringField('Address', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    position = StringField('Position', validators=[DataRequired()])
    plan_id = SelectField('Plan requirement', validators=[DataRequired()],coerce=int)
    submit = SubmitField('Save')

    def validate_email(self, email):
        candidate = Candidate.query.filter_by(email=email.data).first()
        if candidate and candidate.id != self.id.data:
            raise ValidationError('That email is taken. Please choose a different one.')

 

blog/candidates/routes.py
from flask import Blueprint, url_for, render_template, flash,redirect, request
from blog.candidates.forms import AddCandidateForm, EditCandidateForm
from blog.models import Plan, Candidate
from flask_login import login_required
from blog import db

candidates = Blueprint('candidates',__name__)


@candidates.route("/candidate")
@login_required
def index():
    candidates = Candidate.query.all()
    return render_template('candidate/index.html', candidates=candidates)


@candidates.route("/candidate/create", methods=['GET', 'POST'])
def create():
    form = AddCandidateForm()
    form.plan_id.choices = [(row.id, row.title) for row in Plan.query.all()]
    if form.validate_on_submit():
        candidate = Candidate(
            name=form.name.data, 
            email=form.email.data,
            address=form.address.data,
            phone=form.phone.data,
            position=form.position.data,
            plan_id=form.plan_id.data,
        )
        db.session.add(candidate)
        db.session.commit()
        flash('Your candidate has been created!', 'success')
        return redirect(url_for('candidates.index'))
    return render_template('candidate/create.html', form = form)



@candidates.route("/candidate/<int:candidate_id>/edit", methods=['GET', 'POST'])
@login_required
def update(candidate_id):
    candidate = Candidate.query.get_or_404(candidate_id)
    form = EditCandidateForm()
    form.plan_id.choices = [(row.id, row.title) for row in Plan.query.all()]
    if form.validate_on_submit():
        candidate.name = form.name.data
        candidate.email = form.email.data
        candidate.address = form.address.data
        candidate.phone = form.phone.data
        candidate.position = form.position.data
        candidate.plan_id = form.plan_id.data
        db.session.commit()
        flash('Your candidate has been updated!', 'success')
        return redirect(url_for('candidates.update', candidate_id=candidate.id))
    elif request.method == 'GET':
        form.id.data = candidate.id
        form.name.data = candidate.name
        form.email.data = candidate.email
        form.phone.data = candidate.phone
        form.address.data = candidate.address
        form.position.data = candidate.position
        form.plan_id.data = candidate.plan_id
    return render_template('candidate/edit.html', title='Update Post',
                           form=form)

@candidates.route("/candidate/<int:candidate_id>/delete", methods=['POST'])
@login_required
def delete_candidate(candidate_id):
    candidate = Candidate.query.get_or_404(candidate_id)
    db.session.delete(candidate)
    db.session.commit()
    flash('Your candidate has been deleted!', 'success')
    return redirect(url_for('candidates.index'))

blog/templates/candidate/create.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Candidate</legend>
                <div class="form-group">
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.phone.label(class="form-control-label") }}
                    {% if form.phone.errors %}
                        {{ form.phone(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.phone.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.phone(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.address.label(class="form-control-label") }}
                    {% if form.address.errors %}
                        {{ form.address(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.address(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.position.label(class="form-control-label") }}
                    {% if form.position.errors %}
                        {{ form.position(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.position.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.position(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.plan_id.label(class="form-control-label") }}
                    {% if form.plan_id.errors %}
                        {{ form.plan_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.plan_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.plan_id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

blog/templates/candidate/edit.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edit Candidate</legend>
                <div class="form-group">
                    {{ form.id(class="form-control form-control-lg", type="hidden") }}
                    {{ form.name.label(class="form-control-label") }}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.phone.label(class="form-control-label") }}
                    {% if form.phone.errors %}
                        {{ form.phone(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.phone.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.phone(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.address.label(class="form-control-label") }}
                    {% if form.address.errors %}
                        {{ form.address(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.address.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.address(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.position.label(class="form-control-label") }}
                    {% if form.position.errors %}
                        {{ form.position(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.position.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.position(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.plan_id.label(class="form-control-label") }}
                    {% if form.plan_id.errors %}
                        {{ form.plan_id(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.plan_id.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.plan_id(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    
{% endblock content %}

blog/templates/candidate/index.html
{% extends "layout.html" %}
{% block content %}
<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Email</th>
			<th>Position</th>
			<!-- <th>Plan</th> -->
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
		{% for item in candidates %}
		<tr>
			<td>{{ item.name }}</td>
			<td>{{ item.email }}</td>
			<td>{{ item.position }}</td>
			<!-- <td>{{ item.plan.title }}</td> -->
			<td>
				<a href="{{ url_for('candidates.update', candidate_id=item.id) }}"><button type="button" class="btn btn-info btn-sm m-1">Edit</button></a>
				<button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal{{item.id}}">Delete</button>
			</td>
		</tr>   
		<div class="modal fade" id="deleteModal{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="deleteModalLabel">Delete Candidate?</h5>
						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
						<form action="{{ url_for('candidates.delete_candidate', candidate_id=item.id) }}" method="POST">
							<input class="btn btn-danger" type="submit" value="Delete">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</tbody>
</table>



{% endblock content %}